USE [master]
GO

/****** Object:  Database [Marketing]    Script Date: 10/24/2025 4:36:43 PM ******/
DROP DATABASE [Marketing]
GO

/****** Object:  Database [Marketing]    Script Date: 10/24/2025 4:36:43 PM ******/
CREATE DATABASE [Marketing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Marketing', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Marketing.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Marketing_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Data\Marketing_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Marketing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Marketing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Marketing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Marketing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Marketing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Marketing] SET ARITHABORT OFF 
GO

ALTER DATABASE [Marketing] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Marketing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Marketing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Marketing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Marketing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Marketing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Marketing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Marketing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Marketing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Marketing] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Marketing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Marketing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Marketing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Marketing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Marketing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Marketing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Marketing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Marketing] SET RECOVERY FULL 
GO

ALTER DATABASE [Marketing] SET  MULTI_USER 
GO

ALTER DATABASE [Marketing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Marketing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Marketing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Marketing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Marketing] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Marketing] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Marketing] SET QUERY_STORE = ON
GO

ALTER DATABASE [Marketing] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Marketing] SET  READ_WRITE 
GO


